### ISSUE TITLE
Project just initialized doesn't work (Vitest + SSR + TypeScript)

### ISSUE THREAD

**Issue by Aex12** [solidjs/solid-start#245] opened 2022-08-12 17:31 UTC
### Steps to reproduce
Initialize a new project using `npm init solid@next`
Select the following options: Vitest, SSR enabled, Typescript enabled.
Install deps: `npm install`
Run the dev server: `npm run dev`
Open the browser on localhost:300.

### The bug
The counter doesn't work. You can see <header></header> on the top of the page as a plain string, without rendering.

If you run the tests with `npm run test`, Vitest will complain with the following error: `Failed to load $CWD/node_modules/solid-start/vitest.setup.ts`.

### Workaround
Starting a project with Bare + SSR + Typescript work as expected, but there is no testing library.

**Comment by orenelbaum** [comment] 2022-12-04 06:30
This is fixed now. Also is seems to be a duplicate of https://github.com/solidjs/solid-start/issues/24
Either way this issue can be closed.

**Comment by atk** [comment] 2022-12-04 08:07
No, for SSR, you need to change the configuration so test.transformMode will detect the tests as SSR, see https://vitest.dev/config/#transformmode

**Closed** 2022-12-19 05:02 UTC
