### ISSUE TITLE
errors running `solid-start start` ->. some aws deps -> no issues with dev mode

### ISSUE THREAD

**Issue by quantuminformation** [solidjs/solid-start#482] opened 2022-11-26 17:56 UTC
having fun with aws 

<img width="1340" alt="image" src="https://user-images.githubusercontent.com/216566/204102465-f3c05d9c-c7e8-4090-b7a5-befc6eccdcb6.png">

we not using AWS, so no ideas about that one 

and another one we have no idea about

<img width="1313" alt="image" src="https://user-images.githubusercontent.com/216566/204102532-cc0195d7-7b5d-4356-a7e3-a675e402c5a9.png">

**Comment by quantuminformation** [comment] 2022-11-26 19:14
bcryptjs removed one error

**Comment by Bramas** [comment] 2022-11-27 08:16
Hi, I have the same error presented here #481 
It seems the build process is broken when some packages are used (also introducing errors that are unrelated like this aws package)
In my issue i presented a very simple way to reproduce.

**Comment by Bramas** [comment] 2022-11-27 09:30
I solved my problem here #481 

I think you should just add some packages in the file `vite.config.ts`:
add the option:
```js
ssr: {
    external: ["LIB1", "LIB2"],
  }
```
where LIB* are native packages that introduced the error (not mock-aws-s3, but some packages in your package.json, maybe the best way is to put them all here and try to remove them one by one)

**Comment by ryansolid** [comment] 2022-12-22 04:16
Yeah these stack trace actually say very little. I'd recommend externalizing the dependencies and leaving node to do its thing here. It looks like these are perhaps cjs and there is challenges importing it with esm. Also no idea on the AWS dep. If that doesn't work need a reproduction.

**Comment by OrJDev** [comment] 2022-12-23 08:32
If you are using bcrypt, it should be externalized (and bcrypt is using nock and mock-aws-3), so this is probably where this is coming from.

**Comment by ryansolid** [comment] 2023-12-18 23:18
In setting up for SolidStarts next Beta Phase built on Nitro and Vinxi we are closing all PRs/Issues that will not be merged due to the system changing. If you feel your issue was closed in mistake. Feel free to re-open it after updating/testing against 0.4.x release. Thank you for your patience.  See https://github.com/solidjs/solid-start/pull/1139 for more details.

**Closed by ryansolid** 2023-12-18 23:18 UTC
Labels: bug, needs reproduction
