### ISSUE TITLE
Two routes page render at same time

### ISSUE THREAD

**Issue by harshmangalam** [solidjs/solid-start#493] opened 2022-11-30 07:20 UTC
My folder structure looks like this

```
- routes
    - (auth).tsx
    - (auth)
        - login.tsx
    - [...404].tsx

```

When i remove `(auth).tsx` from `routes` now when i visit `/login`  it render both `404 page` and `login` page.
And `<HttpStatusCode code={404} />` folder will  throw error
`TypeError: Cannot read properties of null (reading 'nextSibling')`

**Comment by m4rvr** [comment] 2022-12-01 19:00
I can confirm this happens for me too when navigating from the dynamic route `/tool/[slug]` to the index route `/`.
Sometimes it also renders the dynamic route twice below the index route.

https://user-images.githubusercontent.com/6840287/205135449-2941ff11-b70d-4c44-a36a-710b00448b01.mp4

**Comment by ryansolid** [comment] 2022-12-22 04:38
Might be caused by a hydration issue triggering the rest. Reproduction would be good thanks.

**Comment by m4rvr** [comment] 2022-12-22 13:44
> Might be caused by a hydration issue triggering the rest. Reproduction would be good thanks.

Thanks, Ryan! The reproduction can be found in the mentioned issue #502.

**Comment by ryansolid** [comment] 2023-12-18 23:19
In setting up for SolidStarts next Beta Phase built on Nitro and Vinxi we are closing all PRs/Issues that will not be merged due to the system changing. If you feel your issue was closed in mistake. Feel free to re-open it after updating/testing against 0.4.x release. Thank you for your patience.  See https://github.com/solidjs/solid-start/pull/1139 for more details.

**Closed by ryansolid** 2023-12-18 23:19 UTC
Labels: bug, needs reproduction
