### ISSUE TITLE
Weird behaviors with streaming renderer and Suspend/ErrorBoundary, am I doing it wrong?

### ISSUE THREAD

**Issue by Hubro** [solidjs/solid-start#592] opened 2022-12-26 12:36 UTC
I'm making a (toy) dashboard application where I want to display the current status of all my Kubernetes deployments. This seems like the ideal use case for streaming, I can render the entire UI and all the dashboard widgets right away, then stream the actual data for each widget as it completes.

However, it's behaving quite weirdly, and I'm not sure if it's because I'm doing something wrong or because this is all still experimental.

This is currently my only page:

```tsx
import { createEffect } from "solid-js";
import { useRouteData } from "solid-start";
import { createServerData$ } from "solid-start/server";
import DeploymentStatus from "~/components/DeploymentStatus";
import { getDeploymentStatus } from "~/k8s";

export function routeData() {
  return {
    stagingStatus: createServerData$(async () => {
      return await getDeploymentStatus(
        "3dbolig-staging",
        "deployment-3dbolig-staging"
      );
    }),
    prodStatus: createServerData$(async () => {
      return await getDeploymentStatus(
        "3dbolig-prod",
        "deployment-3dbolig-prod"
      );
    }),
    iglandStatus: createServerData$(async () => {
      return await getDeploymentStatus(
        "3dbolig-igland",
        "deployment-3dbolig-igland"
      );
    }),
  };
}

export default function Home() {
  const { stagingStatus, prodStatus, iglandStatus } =
    useRouteData<typeof routeData>();

  createEffect(() => {
    console.log(stagingStatus());
  });

  return (
    <main class="container">
      <h1 class="text-2xl font-bold mb-8 text-center">3dbolig status</h1>

      <DeploymentStatus statusResource={stagingStatus} />
      <DeploymentStatus statusResource={prodStatus} />
      <DeploymentStatus statusResource={iglandStatus} />
    </main>
  );
}
```

So basically I'm fetching 3 separate async resources in the route data. Each resource is passed down to the `DeploymentStatus` component to be rendered:

```tsx
import {
  createEffect,
  ErrorBoundary,
  JSX,
  Resource,
  Show,
  Suspense,
} from "solid-js";
import { Component } from "solid-js";
import * as k8s from "~/k8s";

interface DeploymentStatusProps {
  statusResource: Resource<k8s.DeploymentStatus | undefined>;
}

const DeploymentStatus: Component<DeploymentStatusProps> = function (props) {
  const { statusResource } = props;

  createEffect(() => {
    console.log(statusResource());
  });

  return (
    <div>
      <DeploymentStatusBox>
        <Suspense fallback="Loading...">
          <ErrorBoundary fallback={(e) => <>Oh no, we crashed: {e}</>}>
            <Show when={statusResource()}>
              Deployment: {statusResource()!.name}
            </Show>
          </ErrorBoundary>
        </Suspense>
      </DeploymentStatusBox>
    </div>
  );
};

interface DeploymentStatusBoxProps {
  children: JSX.Element;
}

const DeploymentStatusBox: Component<DeploymentStatusBoxProps> = function ({
  children,
}) {
  return <div class="p-2">{children}</div>;
};

export default DeploymentStatus;
```

---

## Weird behavior number 1

I have to use a `Show` component, even though everything is wrapped in `Suspense`. For some reason, after the resource has finished loading, the value is still `undefined` for a moment, which causes the `.name` access to crash. Isn't this strange? Shouldn't the `Suspend` component ensure that the contents is only rendered once the resource is actually loaded? (i.e. no longer `undefined`).

## Weird behavior number 2

When an error occurs, the error value is `undefined` until the entire page is finished loading. In other words, the error boundary component is immediately shown, but it says `"Oh no, we crashed: undefined"` until the page finishes loading, after which it shows the actual error.

Demo:

https://user-images.githubusercontent.com/597206/209548694-f8eb5d90-6d38-4805-b5e6-14bf05b03ca5.mp4

## Weird behavior number 3

If I don't slow down the network speed, any content inside `Suspend` is doubled, but not every time. It seems like a timing issue. Is this because I'm doing something wrong, or is it a bug?

https://user-images.githubusercontent.com/597206/209549106-be6e7ab9-4641-40d3-9e5d-1f7ba5627a05.mp4

**EDIT:** After some experimentation, this seems to be because I'm using raw text rather than HTML elements. If I wrap my messages inside `div`s or `p`s inside the `Suspense` and `fallback=...`, then the contents is properly replaced. I posted this as a bug report: https://github.com/solidjs/solid-start/issues/593.

---

`package.json`:

```json
{
  "name": "3dbolig-status",
  "scripts": {
    "dev": "solid-start dev",
    "build": "solid-start build",
    "start": "solid-start start"
  },
  "type": "module",
  "devDependencies": {
    "@tailwindcss/language-server": "^0.0.10",
    "autoprefixer": "^10.4.12",
    "postcss": "^8.4.18",
    "prettier": "^2.8.1",
    "solid-start-node": "^0.2.0",
    "tailwindcss": "^3.2.0",
    "typescript": "^4.9.4",
    "typescript-language-server": "^2.2.0",
    "vite": "^3.1.8"
  },
  "dependencies": {
    "@kubernetes/client-node": "^0.18.0",
    "@solidjs/meta": "^0.28.0",
    "@solidjs/router": "^0.6.0",
    "solid-js": "^1.6.2",
    "solid-start": "^0.2.0",
    "undici": "^5.11.0"
  },
  "engines": {
    "node": ">=16"
  }
}
```

`entry-server.tsx`:

```tsx
import {
  StartServer,
  createHandler,
  renderStream,
} from "solid-start/entry-server";

export default createHandler(
  renderStream((event) => <StartServer event={event} />)
);
```

```
➜ node --version
v18.12.1
```

**Comment by indeyets** [comment] 2023-02-03 22:08
I see similar problem with Suspense. here's the repo which can be used to reproduce behavior:

https://github.com/indeyets/solid-bug

1. yarn
2. yarn dev
3. open http://localhost:5173/s/test
4. refresh page (Cmd-R)

**Comment by ryansolid** [comment] 2023-12-18 23:38
In setting up for SolidStarts next Beta Phase built on Nitro and Vinxi we are closing all PRs/Issues that will not be merged due to the system changing. If you feel your issue was closed in mistake. Feel free to re-open it after updating/testing against 0.4.x release. Thank you for your patience.  See https://github.com/solidjs/solid-start/pull/1139 for more details.

**Closed by ryansolid** 2023-12-18 23:38 UTC
