### ISSUE TITLE
Error: Unrecoverable Hydration Mismatch. No template for key: 

### ISSUE THREAD

**Issue by shrubway** [solidjs/solid-start#904] opened 2023-06-12 17:04 UTC
I get this `Clear errors and retry` warning button on  for a fresh install of SoldStart with mdx and when I press it I get this error in the console:

```
ErrorBoundary.tsx:27 Error: Unrecoverable Hydration Mismatch. No template for key: 0-0-0-0-0-0-0-0-0-1-0-0-2-0-1-1-0-0-3
    at getNextElement (dev.js:274:26)
    at Object.fn (dev.js:617:43)
    at runComputation (dev.js:695:22)
    at updateComputation (dev.js:678:3)
    at Object.readSignal (dev.js:611:67)
    at resolveChildren (dev.js:976:82)
    at resolveChildren (dev.js:980:22)
    at resolveChildren (dev.js:976:66)
    at resolveChildren (dev.js:976:66)
```

my packages.json:

{
```
  "name": "solidstart-blog",
  "lockfileVersion": 3,
  "requires": true,
  "packages": {
    "": {
      "name": "solidstart-blog",
      "dependencies": {
        "@solidjs/meta": "^0.28.2",
        "@solidjs/router": "^0.8.2",
        "solid-js": "^1.7.2",
        "solid-mdx": "^0.0.6",
        "solid-start": "^0.2.26",
        "undici": "^5.15.1"
      },
      "devDependencies": {
        "@mdx-js/rollup": "^2.2.1",
        "solid-start-node": "^0.2.19",
        "typescript": "^4.9.4",
        "vite": "^4.1.4"
      },
      "engines": {
        "node": ">=16"
      }
    },
```

It is not fixed after clearing the cach. Appreciate your tips to resolve it.

**Comment by Bluefinger** [comment] 2023-06-28 14:06
The issue is with `solid-mdx`, particularly due to the fact it hasn't been updated in a long while and has some issues with how it handles the props for the context and children. Basically fixed once `splitProps` is used. I opened a PR there, so hopefully it gets merged.

**Comment by avivdaniel** [comment] 2023-08-01 09:55
Facing the same issue, any updates?

**Comment by Bluefinger** [comment] 2023-08-02 07:30
I've had the PR for `solid-mdx` open for a while now, but there seems to be no response from the maintainer, and the repo itself hasn't been updated in a while, so I wonder if the maintainer has abandoned it or not wanting to maintain it any longer. If no further response from them, the alternative is to move away from `solid-mdx` and provide a different implementation that fixes the problem.

**Comment by ryansolid** [comment] 2023-12-19 17:23
In setting up for SolidStarts next Beta Phase built on Nitro and Vinxi we are closing all PRs/Issues that will not be merged due to the system changing. If you feel your issue was closed by mistake. Feel free to re-open it after updating/testing against 0.4.x release. Thank you for your patience.  See https://github.com/solidjs/solid-start/pull/1139 for more details.

**Closed by ryansolid** 2023-12-19 17:23 UTC
