### ISSUE TITLE
[Bug?]: Route group with API does not work

### ISSUE THREAD

**Issue by ryoid** [solidjs/solid-start#1176] opened 2023-12-25 07:50 UTC
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Current behavior 😯

Creating route group with API Route returns 404.

### Expected behavior 🤔

API route shout work

### Steps to reproduce 🕹

Steps:

1. `pnpm create solid` basic
2. Create route group with API route `/routes/(group)/endpoint.tsx`
```tsx
// folder structure
|-- routes/
    |-- (group)
        |-- page.tsx         // http://example.com/page - works
        |-- endpoint.tsx     // http://example.com/endpoint - not found

// endpoint.tsx
export function GET() {
  return new Response("Hello World")
}

// page.tsx
export default function Page() {
  return (
    <main>
      <h1>Page</h1>
    </main>
  )
}
```
4. Go to `http://localhost:3000/endpoint`, 404
5. Go to `http://localhost:3000/page`, page in same route group displays

### Context 🔦

Trying to group API routes that generate `sitemap.xml` and `robots.txt`

```
|-- routes/
    |-- (sitemeta)
        |-- sitemap.xml.ts
        |-- robots.txt.ts
```

Reproduction
https://github.com/ryoid/solidstart-bug-grouped-api-route

### Your environment 🌎

```shell
Node 20.10.0

"@solidjs/meta": "^0.29.2",
"@solidjs/router": "^0.10.5",
"@solidjs/start": "^0.4.2",
"solid-js": "^1.8.7",
"vinxi": "0.0.54"
https://github.com/ryoid/solidstart-bug-grouped-api-route/blob/main/package.json
```

**Comment by jzohdi** [comment] 2023-12-26 12:09
Hi @ryoidI started to inspect this issue and have opened a pull request [here](https://github.com/solidjs/solid-start/pull/1181) to show what I believe the issue to be.

@ryansolid could I be assigned this issue? Note: I am still in the process of testing/adding tests to the PR

**Comment by apademide** [comment] 2023-12-30 13:06
I stumbled upon the same issue yesterday and [described it here on Discord](https://discord.com/channels/722131463138705510/1190336072434057256). 

In the current implementation, it's expected that those grouping segments in API routes don't work, because they're just not handled at all. [UI routes will replace any `/(...)` matching segment](https://github.com/solidjs/solid-start/blob/a9b4b0532f76ce9f0c20545b4f6732a126771a7f/packages/start/shared/routes.ts#L84), but [API routes won't do anything on them](https://github.com/solidjs/solid-start/blob/a9b4b0532f76ce9f0c20545b4f6732a126771a7f/packages/start/shared/routes.ts#L104). This means in your repro, you wouldn't be able to access `localhost/endpoint`, but `localhost/(group)/endpoint` would work.

I only hope this is an overlook and not a design choice, since grouping adds as much convenience on API routes as it does with UI ones.

**Comment by jzohdi** [comment] 2023-12-30 13:44
Thanks @apademide for your detailed write up on discord!

A replacement strategy similar to how UI routes implement it for groups would with consideration to maintaining the "scoring" order of routes to match. I can include this in my PR and also be sure to include documentation to the expected behavior to make it clear in the future.

**Closed** 2024-01-04 22:07 UTC
Labels: bug
