### ISSUE TITLE
Duplicate CSS with tailwind

### ISSUE THREAD

**Issue by ghost** [solidjs/solid-start#298] opened 2022-10-06 10:24 UTC
When using solid-start with tailwind, it creates multiple instances of the generated css styles.

![image](https://user-images.githubusercontent.com/108274890/194289263-4edc0e6a-8dbb-43cd-9ec8-42cce6108bdd.png)
These two contains identical css

It seems to also include more duplication from the pages
![image](https://user-images.githubusercontent.com/108274890/194289722-4b7d82f9-5ffa-4c03-afb9-17847064c364.png)

**Comment by ArekBartnik** [comment] 2022-12-04 04:03
@JonahLund was this issue resolved for you? I can see this duplication of `style` in the `with-tailwindcss` template.

**Comment by quantuminformation** [comment] 2022-12-04 04:42
we get the same 
<img width="618" alt="image" src="https://user-images.githubusercontent.com/216566/205474857-fc7c1d61-b5dd-41de-a67f-f12c97e1e387.png">

**Comment by ArekBartnik** [comment] 2022-12-11 10:07
@JonahLund would you reopen it? it is "dev" only issue but it makes debugging styles harder

**Comment by ArekBartnik** [comment] 2022-12-11 13:37
this problem is caused by https://github.com/solidjs/solid-start/commit/b83372e2b5095d1a0c2e40f861cf6b237970833f
`<InlineStyles />`is included in `dev` and then vite inserts its own inline styles.

**Comment by ryansolid** [comment] 2022-12-19 03:36
Hmm.. the FOUC was a big deal. Lots of complaints. People confused thinking Start was broken. I was told it was near unusable. Now I don't have such hard opinions here, but I can't understate the complaining.

**Comment by ryansolid** [comment] 2023-12-18 21:12
In setting up for SolidStarts next Beta Phase built on Nitro and Vinxi we are closing all PRs/Issues that will not be merged due to the system changing. If you feel your issue was closed in mistake. Feel free to re-open it after updating/testing against 0.4.x release. Thank you for your patience.  See https://github.com/solidjs/solid-start/pull/1139 for more details.

**Closed by ryansolid** 2023-12-18 21:12 UTC
Labels: bug
