### ISSUE TITLE
customElement with interop

### ISSUE THREAD

**Issue by xluk9** [solidjs/solid-start#539] opened 2022-12-16 21:29 UTC
Hello, I've been trying to create a custom web component from solidjs. I used the [example as is from solid-element](https://studio.webcomponents.dev/edit/yGRb00wV4AMncPupRmA9/src/index.jsx?p=stories) in a freshly solid-start app, with bootstrap 5 and tom-select. This is the `index.tsx` page
```tsx
import { JSXElement, onMount, createSignal } from "solid-js";
import { PropAliases, renderToString } from "solid-js/web";
import { Title } from "solid-start";
import TomSelect from "tom-select";
import 'tom-select/dist/css/tom-select.bootstrap5.css'
import Counter from "~/components/Counter";
import { customElement } from "solid-element";
import { register } from 'component-register';

function Item(props) {
  return <div class=''>
          <div class="fw-bold">{props.children}</div>
          <div class="">Some normal</div>
        </div>
}

const style = `div * {
  font-size: 200%;
}

span {
  width: 4rem;
  display: inline-block;
  text-align: center;
}

button {
  width: 4rem;
  height: 4rem;
  border: none;
  border-radius: 10px;
  background-color: seagreen;
  color: white;
}`;

customElement("my-item", () => {
const [count, setCount] = createSignal(0);
return (
<div>
<style>{style}</style>
<button onClick={() => setCount(count() - 1)}>-</button>
<span>{count}</span>
<button onClick={() => setCount(count() + 1)}>+</button>
</div>
);
});


export default function Home() {
  let s : HTMLElement;
  onMount(() =>{
    new TomSelect(`#${s.getAttribute('id')}`,{
      maxItems: 3,
      render: {
        option: (data) => {
          return `<my-item></my-item>`;
        }
      }
    });
  })
  return (
    <main class="px-5 py-5">
      <Title>Hello World</Title>
      <select class="form-select" aria-label="Default select example" ref={s} id="dcd222">
      <option selected>Open this select menu</option>
      <option value="1">One</option>
      <option value="2">Two</option>
      <option value="3">Three</option>
      </select>
    </main>
  );
}
```

But I get 

![Screen Shot 2022-12-16 at 10 19 46 PM](https://user-images.githubusercontent.com/25955481/208191317-4f051d19-bd94-43e4-af51-207612b0184b.png)

Ideally, I would like to reuse the `<Item>` component, because I need it both outside and inside `tom-select`. Inside to render each element in a drop-down select. Outside in a solidjs page component.

For the time being, I don't need `<Item>` to be reactive, I just want to avoid to repeat the same style/code for rendering the list item in two different function. So, I'm open to see other solutions, like rendering JSX to plain HTML. I've done a little research and read on `dom-expression`, but it seems it needs `babel` compiler and I don't know how to integrate everything with vitejs, solid-start and solidjs.

I appreciate any help.

**Comment by ryansolid** [comment] 2022-12-17 06:09
Yeah if you don't care that these client render only (we don't have SSR/hydration for Solid Element currently), you should be able to just only register `customElement` calls for client build. I think that you could just wrap them in `!isServer` conditions. The problem is there is no DOM on the server and Solid doesn't even try to make DOM elements there for that reason. Everything builds strings on the server.

**Comment by xluk9** [comment] 2022-12-17 11:55
Hi, thank you for the quick reply. I didn't try the `!isServer` solution proposed. I tried insead this, by creating a new root element
```tsx
import { getOwner, onMount } from "solid-js";
import { Title } from "solid-start";

import TomSelect from "tom-select";
import "tom-select/dist/css/tom-select.bootstrap5.css";
import 'bootstrap/dist/css/bootstrap.min.css';
import { render } from "solid-js/web";



export function Item(props) {
  return <>
    <div class="fw-bold">{props.a} </div>
    <div class="">{props.b} </div>
    <div class="">{props.children}</div>
  </>

}

export default function Home() {
  let s: HTMLElement;
  onMount(() => {
    new TomSelect(s,{
      valueField: 'id',
      searchField: 'title',
      maxItems: 2,
      options: [
        {id: 1, title: 'DIY', url: 'https://diy.org'},
        {id: 2, title: 'Google', url: 'http://google.com'},
        {id: 3, title: 'Yahoo', url: 'http://yahoo.com'},
      ],
      render: {
        option: function(data, escape) {

          // Wrap in a new root element
          let el = document.createElement('div');
          render(() => <Item a={data.title} b={data.url}>11</Item>, el)
          return el;

          
        },
        item: function(data)  {
          return "<div>" + data.title + "</div>"
        }
      }
    });
  });
  return (
    <main class="px-5 py-5">
      <Title>Hello World</Title>
      <Item a='2' b='ccc'/>
      <select
        class="form-select"
        aria-label="Default select example"
        ref={s}
      >
      </select>
    </main>
  );
}
```

It works, it renders the `<Item>` component. But I have a couple of doubts

1.  This will lose the reactivity from the main root element, right?
2. Could there be any memory leaks?

I'm kind a new to Solidjs, so still I don't perfectly understand the reactivity model. Can you kindly shed some light on the reactivity part with two different  roots? I will try later with some code to learn about it.

**Comment by ryansolid** [comment] 2022-12-19 03:23
It won't share context but it will be part of the same reactive system. Memory leak could be a concern. `render` returns a dispose method.

**Comment by ryansolid** [comment] 2022-12-22 06:18
Bringing in DOM emulation is not what you want to do in SSR, ever. Super slow. The trick is to make a specific process, but then it likely is per library. Lit team is trying to standardize this a bit, but until then not interested as every webcomponent framework would be a bit different.

In general I'd follow this space: https://github.com/webcomponents-cg/community-protocols/issues

**Closed by ryansolid** 2022-12-22 06:18 UTC
