### ISSUE TITLE
[Bug?]: API routes in file based Route Groups don't work in RC1

### ISSUE THREAD

**Issue by timothyallan** [solidjs/solid-start#1463] opened 2024-05-01 21:40 UTC
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Current behavior 😯

having an API route in a route group gives a 404, whereas in previous v.3 it worked.
I found this previous issue where it apparently was resolved? https://github.com/solidjs/solid-start/issues/1176

### Expected behavior 🤔

I should be able to fire my API from inside a route group.

### Steps to reproduce 🕹

to replicate with a new project:
```
npm init solid@latest
```

create `apiget.tsx` with the following :
```JSX
export function GET() {
  return new Response("Hello World");
}
```
place it in `/routes`, and navigate to `http://localhost:3000/apiget`. Works.

Move `apiget.ts
x` into a new `/routes/(blah)/` folder and refresh `http://localhost:3000/apiget`, and you'll get a 404.

![Screenshot 2024-05-01 at 3 29 30 PM](https://github.com/solidjs/solid-start/assets/1995135/f143a002-f7f5-441e-844c-2df14fafcf3b)

For fun, change `apiget.tsx` to contain the following:

```JSX
export default function ApiGet() {
  return <div>Why do I work in a Route Group, but the API call doesn't?</div>;
}
```
now refresh `http://localhost:3000/apiget`, and you'll get the component output.

### Context 🔦

I have a URL which needs to dynamically redirect to an image after some database checks. That URL is nested in some layout files with nested contexts.

### Your environment 🌎

```shell
Solid Start rc1, MacOS, Node 20.12.2
```

**Comment by ryansolid** [comment] 2024-05-02 23:53
Yeah in 0.5 I seperated the API route handling and simplified the matcher. However, I ended up reverting this separation later in the release  which is why things don't look different even though they work completely different now. Given that I brought the routes back in I suppose it is fair to see if we can support the other syntax. I do caution in general that co-locating is a poor pattern here as we resolve all API routes before render routes, so things like catch alls won't work perhaps as you might expect when shared in the same scope as page routes. But I see very little reason not to allow them to work under things like route groups given where we landed.

**Comment by timothyallan** [comment] 2024-05-03 01:35
Cool thanks Ryan, just to add some more context, the scenario is like this:

For users to view their content, they go to: `mydomain.com/viewer/userSlug`, to fetch a thumbnail for SEO, the meta tags use `mydomain.com/viewer/userSlug/thumb`.

The `/thumb` needs to be a GET API request as it just 301's to a jpg, and the `/viewer/userSlug` route goes through a bunch of layouts/contexts using Route Groups. With the current setup, `/thumb` simply doesn't work anymore and 404's.

**Comment by ryansolid** [comment] 2024-05-03 15:52
Actually looking at it, it was intended to work. Looks like it was just a small mistake in the regex. Will get this fixed up shortly.

**Closed** 2024-05-03 15:54 UTC
Labels: bug

**Comment by timothyallan** [comment] 2024-05-06 20:32
Just got the RC1 installed, and this is still borked unfortunately. However, I narrowed it down some more to a route with a parameter in it. Minimal repro is this structure:
![Screenshot 2024-05-06 at 2 22 01 PM](https://github.com/solidjs/solid-start/assets/1995135/b4efca77-7142-452a-84f5-526662cffa49)

Where `(viewer).tsx` is just 
```JSX
export default function Viewer() {
  return <div>Viewer</div>;
}
```
and `thumbnail.tsx` is 
```JSX
import { APIEvent } from '@solidjs/start/server';

export async function GET({ request }: APIEvent) {
  console.log(`getting the thumbnail`);
}
```
Navigate to anything like `http://localhost:3000/viewer/abc`
As long as that API route in there, there's a 500. As soon as `thumbnail.tsx` is removed, that route works.
```JSX
[h3] [unhandled] TypeError: Cannot read properties of undefined (reading '$GET')
    at Module.matchAPIRoute (/test/solid-project/node_modules/@solidjs/start/dist/router/routes.js:32:32)
```
