### ISSUE TITLE
Pathless routes + ErrorBoundary not working properly

### ISSUE THREAD

**Issue by m4rvr** [solidjs/solid-start#502] opened 2022-12-02 13:22 UTC
Hey!

Pathless routes and ErrorBoundary doesn't seem to work properly. When switching between routes, the content of the previous route is rendered below the new route.

I noticed that when the children of `<ErrorBoundary />` (`routes/nested/[slug].tsx` file) aren't wrapped with a `<div>` it sometimes works. The same happens with `<Outlet />` (`routes/(app).tsx` file). Wrapping it with a `<div>` breaks it, having it at the root works. IIRC this doesn't happen for non-pathless routes.

Also, the ErrorBoundary doesn't catch errors in production. It works in development and shows the fallback content but in production (deployed on Vercel) the function crashes. I tested this with a non-pathless route in production and it showed the fallback content.

Reproduction:
https://github.com/m4rvr/solid-start-bug

1. npm run dev
2. Go to http://127.0.0.1:3000/nested/foo
3. Click on link "back to home"
4. home route should show content of itself + content of nested route below like this
<img width="226" alt="CleanShot 2022-12-02 at 14 20 12@2x" src="https://user-images.githubusercontent.com/6840287/205301926-534bd708-8dd6-4e6b-bc52-abac79156936.png">

I could imagine that if the pathless routes work properly, the failing ErrorBoundary in production could be fixed too.

(probably related issue #493 )

**Comment by binajmen** [comment] 2022-12-26 21:11
Hello @m4rvr,

Thank you for documenting this bug. I recently hit the same issue of `ServerError` not being catched by the default `ErrorBoundary` in `root.tsx`.

When such event occurs, my node instance on Fly.io crashes and restarts.

What would be a temporary workaround? Not throwing? Throwing something different (`Response`, `Error`)?

**Comment by binajmen** [comment] 2022-12-28 07:53
I'm able to reproduce the same issue in non-pathless routes: https://github.com/solidjs/solid-start/issues/596

**Comment by ryansolid** [comment] 2023-12-18 23:22
In setting up for SolidStarts next Beta Phase built on Nitro and Vinxi we are closing all PRs/Issues that will not be merged due to the system changing. If you feel your issue was closed in mistake. Feel free to re-open it after updating/testing against 0.4.x release. Thank you for your patience.  See https://github.com/solidjs/solid-start/pull/1139 for more details.

**Closed by ryansolid** 2023-12-18 23:22 UTC
Labels: bug
