### ISSUE TITLE
Getting "Importing a module script failed" errors a lot in prod.

### ISSUE THREAD

**Issue by milesj** [solidjs/solid-start#764] opened 2023-02-22 01:12 UTC
We're constantly seeing this error in Sentry:

<img width="1250" alt="Screenshot 2023-02-21 at 5 08 53 PM" src="https://user-images.githubusercontent.com/143744/220494800-ac8bc81f-1d91-4284-bea6-f65047ca4305.png">

The error doesn't really make sense. Sentry only has this in it's breadcrumbs:

```
GET https://moonrepo.app/assets/styles.84847c59.js FAILED

{__span: 8bae4e7eb457b6bf}
```

This file exists though and we're unable to reproduce any of these failures on our end. We believe this is coming from Vite and is some kind of caching problem, but have been unable to find a root cause. We also haven't deployed in days, so the cache being stale doesn't apply here, as these are all for fresh unique users.

Hoping someone here may know more.

**Comment by boehs** [comment] 2023-02-24 22:12
1. Cool to see start being used in production!
2. This is... Obviously very hard to debug considering you have no reproduction

**Comment by boehs** [comment] 2023-02-24 22:14
Wait, one idea. I have personally experienced inexplicable hydration errors only on production domains when proxying with Cloudflare......

**Comment by milesj** [comment] 2023-02-25 19:17
We actually have SSR turned off because of constant hydration problems, so this app is purely static atm.

We're also using digitalocean app platform and I don't believe it uses cloudflare, but it may be another CDN around it. I'll dig more.

**Comment by ryansolid** [comment] 2023-12-19 00:34
In setting up for SolidStarts next Beta Phase built on Nitro and Vinxi we are closing all PRs/Issues that will not be merged due to the system changing. If you feel your issue was closed by mistake. Feel free to re-open it after updating/testing against 0.4.x release. Thank you for your patience.  See https://github.com/solidjs/solid-start/pull/1139 for more details.

**Closed by ryansolid** 2023-12-19 00:34 UTC
