### ISSUE TITLE
`npm` unable to resolve dependency tree , `vite@"^4.1.4"` vs `vite@"^3.1.8"`. Pnpm seems to work though

### ISSUE THREAD

**Issue by Bersaelor** [solidjs/solid-start#779] opened 2023-02-28 16:22 UTC
So, I followed the [start.solidjs Project setup](https://start.solidjs.com/getting-started/project-setup) but didn't get past the third step:

```bash
npm init solid@latest
# chose the bare config
npm install
```
and the result was:

```bash
❯ npm install
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR! 
npm ERR! While resolving: lambda@undefined
npm ERR! Found: vite@4.1.4
npm ERR! node_modules/vite
npm ERR!   dev vite@"^4.1.4" from the root project
npm ERR!   peer vite@"*" from solid-start-aws@0.2.22
npm ERR!   node_modules/solid-start-aws
npm ERR!     peerOptional solid-start-aws@"*" from solid-start@0.2.22
npm ERR!     node_modules/solid-start
npm ERR!       solid-start@"^0.2.22" from the root project
npm ERR!       8 more (solid-start-aws, solid-start-cloudflare-pages, ...)
npm ERR!   6 more (solid-start-cloudflare-pages, ...)
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer vite@"^3.1.8" from solid-start@0.2.22
npm ERR! node_modules/solid-start
npm ERR!   solid-start@"^0.2.22" from the root project
npm ERR!   peer solid-start@"*" from solid-start-aws@0.2.22
npm ERR!   7 more (solid-start-cloudflare-pages, ...)
npm ERR! 
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR! 
npm ERR! 
npm ERR! For a full report see:
npm ERR! /Users/konradfeiler/.npm/_logs/2023-02-28T16_13_40_923Z-eresolve-report.txt

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/konradfeiler/.npm/_logs/2023-02-28T16_13_40_923Z-debug-0.log
```

Here is the `package.json` that was created by `npm init solid@latest`:

```
{
  "name": "solidtest",
  "scripts": {
    "dev": "solid-start dev",
    "build": "solid-start build",
    "start": "solid-start start"
  },
  "type": "module",
  "devDependencies": {
    "@types/node": "^18.11.18",
    "esbuild": "^0.14.54",
    "postcss": "^8.4.21",
    "solid-start-node": "^0.2.19",
    "typescript": "^4.9.4",
    "vite": "^4.1.4"
  },
  "dependencies": {
    "@solidjs/meta": "^0.28.2",
    "@solidjs/router": "^0.7.0",
    "solid-js": "^1.6.11",
    "solid-start": "^0.2.22",
    "undici": "^5.15.1"
  },
  "engines": {
    "node": ">=16.8"
  }
}
```

**Comment by joshball** [comment] 2023-02-28 20:02
I just ran into this as well. Both yarn and pnpm work fine, but not npm.
My error is a bit different (`While resolving: base-solid@undefined`) but otherwise the smae.
It looks like it is related to this commit: https://github.com/solidjs/solid-start/commit/e51e2ec4385b5ab8333a9d5c86c36e8cf2d5c031. 
Vite changing:
"vite": "^3.2.5" to "vite": "^4.1.4"
Which is breaking the build.
Returning vite to ^3.2.5 seems to work for now.

**Comment by Niclassg** [comment] 2023-03-02 18:54
Just to chime in with my exact steps aswell
```
npm init solid@latest   
Need to install the following packages:
  create-solid@0.2.22
Ok to proceed? (y)

create-solid version 0.2.9

Welcome to the SolidStart setup wizard!

There are definitely bugs and some feature might not work yet.
If you encounter an issue, have a look at https://github.com/solidjs/solid-start/issues and open a new one, if it is not already tracked.

√ Which template do you want to use? » with-tailwindcss
√ Server Side Rendering? ... yes
√ Use TypeScript? ... yes
found matching commit hash: e82f707cd026e00a46148aef3b4c05c81ceae7f0
downloading https://github.com/solidjs/solid-start/archive/e82f707cd026e00a46148aef3b4c05c81ceae7f0.tar.gz to C:\Users\username\.degit\github\solidjs\solid-start/e82f707cd026e00a46148aef3b4c05c81ceae7f0.tar.gz
extracting /examples/with-tailwindcss from C:\Users\username\.degit\github\solidjs\solid-start/e82f707cd026e00a46148aef3b4c05c81ceae7f0.tar.gz to D:\repos\next-holiday\.solid-start
cloned solidjs/solid-start#main to D:\repos\next-holiday\.solid-start
✔ Copied project files

Next steps:
  1: npm install
  2: npm run dev -- --open

To close the dev server, hit Ctrl-C
D:\repos\next-holiday> npm i
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR!
npm ERR! While resolving: next-holiday@undefined
npm ERR! Found: vite@4.1.4
npm ERR! node_modules/vite
npm ERR!   dev vite@"^4.1.4" from the root project
npm ERR!   peer vite@"*" from solid-start-aws@0.2.22
npm ERR!   node_modules/solid-start-aws
npm ERR!     peerOptional solid-start-aws@"*" from solid-start@0.2.22
npm ERR!     node_modules/solid-start
npm ERR!       solid-start@"^0.2.22" from the root project
npm ERR!       8 more (solid-start-aws, solid-start-cloudflare-pages, ...)
npm ERR!   6 more (solid-start-cloudflare-pages, ...)
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peer vite@"^3.1.8" from solid-start@0.2.22
npm ERR! node_modules/solid-start
npm ERR!   solid-start@"^0.2.22" from the root project
npm ERR!   peer solid-start@"*" from solid-start-aws@0.2.22
npm ERR!   7 more (solid-start-cloudflare-pages, ...)
npm ERR!
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
```

**Comment by darrenbarklie** [comment] 2023-03-04 01:35
Also reproducing this installing with npm:
```bash
Could not resolve dependency:
peer vite@"^3.1.8" from solid-start@0.2.22
```

**Comment by golamrabbiazad** [comment] 2023-03-08 10:42
If this kind of problem occurs, when you `init solid@latest` the first time it will save the cache version of the template you choose. Later in the template's pkg version changed and you try to install the latest version it will compare with the cache version now you get ERESOLVE unable to resolve the dependency tree. tada 👋

Make sure clear the `.caches` of whichever pkg manager you use.

**Comment by Moudoux** [comment] 2023-03-11 16:48
This happens even if you delete whatever cache folder you have. It fails in e.g. docker builds. The problem appears to occur if there is no package-lock.json specifying exact versions. The only fix I've found is to update all dependencies to the latest version, there doesn't seem to be any way to use old versions of solidjs.

**Comment by ryansolid** [comment] 2023-04-04 22:39
Ok I think in 0.2.25 we are all good and back p to date. I didn't have any issues with the `npm i` at least. Just had a really rough Vite 4 migration. I hope everything is good now. 

Reopen if not.

**Closed by ryansolid** 2023-04-04 22:39 UTC
