### ISSUE TITLE
Unexpected behaviour submitting form using `createRouteData`

### ISSUE THREAD

**Issue by adoublef** [solidjs/solid-start#943] opened 2023-07-21 00:07 UTC
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Current behavior 😯

As the [example]((https://stackblitz.com/github/adoublef-js/solid-js?file=README.md)) demonstrates, when using `createRouteAction` to submit a form action, it fails when defined inside a component that is located outside the `routes` directory. The `Card` component also uses a `createRouteAction` method but is not using a form. this component seems to trigger the action regardless of where it is defined.

### Expected behavior 🤔

Given both `CounterForm` and `CounterCard` both include a `createRouteAction` method inside them, i expected both to behave the same. Given the `CounterCard` triggers the action when defined inside/ouside the route directory, I expect the form action to be the same

### Steps to reproduce 🕹

Steps:

1. open [stackblitz](https://stackblitz.com/github/adoublef-js/solid-js?file=README.md)
2. using first form to make a submission, an alert will indicate that the action was triggered
3. click remove button in both the first and second list, they should both behave the same
4. use the second form to make a submission, only the `onclick` alert will get triggered.

### Context 🔦

understanding the limits of actions. the docs dont seem to state this is not possible, but given I am having issues I would like to know if it's advisable or not. 

### Your environment 🌎

```shell
System:
WSL2
```

**Comment by adoublef** [comment] 2023-07-21 00:10
If this is a case that actions related to forms are supposed to be bounded to the a page only, may be appropriate to state it explicitly on the docs? as it's a bit confusing

**Comment by edivados** [comment] 2023-07-21 01:04
The weird behavior is caused by this `async (formData: FormData, { ...rest })`. Change `{ ...rest }` to  '_' for example lik it is in PageForm and it will work. I have no idea why that is would also be interested in knowing.

**Comment by adoublef** [comment] 2023-07-21 08:12
ah nice catch, I didn't see the, this actually made be learn I need to deconstruct the fetch method from the `APIEvent` instead of using the in-built fetch and that still worked to. But yh I dont think its a signal so unsure why a spread failed if you can deconstruct.

**Comment by ryansolid** [comment] 2023-12-19 17:25
In setting up for SolidStarts next Beta Phase built on Nitro and Vinxi we are closing all PRs/Issues that will not be merged due to the system changing. If you feel your issue was closed by mistake. Feel free to re-open it after updating/testing against 0.4.x release. Thank you for your patience.  See https://github.com/solidjs/solid-start/pull/1139 for more details.

**Closed by ryansolid** 2023-12-19 17:25 UTC
Labels: bug
