### ISSUE TITLE
dev fails when the path to the project has a directory with spaces in its name

### ISSUE THREAD

**Issue by ivoilic** [solidjs/solid-start#436] opened 2022-11-13 23:25 UTC
Setup a new project using the start and the first dev run errored out because a parent directory had spaces in its name:
```
✘ [ERROR] Could not resolve "/Users/user/hello"

failed to load config from /Users/user/hello
error when starting dev server:
Error: Build failed with 1 error:
error: Could not resolve "/Users/user/hello"
```
The path should be `/Users/user/hello world/project`

**Comment by Senbonzakura1234** [comment] 2022-11-15 03:14
I'm not sure this is a bug or not, but naming a folder with space in its name and place project folder in `C:/Users/{username}` have never been best practice and people always try to avoid doing them.
1/ Use dash `-` or underscore `_` instead of space or just don't separate characters at all and capitalized 1st character of each word instead. Not just solid, there are significant amount of packages that expected you not to put space in folder's name. So in the end even if solid team resolve this, you shouldn't do it in the future. 
2/ Place your project in `D:/workspace` or `E:/workspace`. JavaScript project has tendencies to pollute your diskspace with it's `node_modules` folders, so you better put them there.

**Comment by ivoilic** [comment] 2022-11-15 05:45
Yes, obviously this is bad practice and of course I moved my project to a different folder. It's an edge case but still a bug.

**Comment by kevintyj** [comment] 2022-12-17 12:14
Many cloud providers and iCloud (the one I use) and gDrive defaults with folders with spaces in them. While I am unsure of how google handles file names on the OS, for apple, renaming the iCloud folder will result in iCloud Drive functionality to stop working. 
The reason why I place some projects inside iCloud is for projects that I don't put on Github (or any other git providers) but still want a remote copy of for backup.  
I'm pretty sure this is an issue with some dependency with solid start as I've seen the same error on some React Native (non expo) projects. 
But this is a annoying issue :(

**Comment by ryansolid** [comment] 2022-12-21 22:48
Duplicate of #401

**Closed by ryansolid** 2022-12-21 22:48 UTC
