### ISSUE TITLE
[Feature?]: /examples working Stackblitz

### ISSUE THREAD

**Issue by birkskyum** [solidjs/solid-start#1171] opened 2023-12-22 01:59 UTC
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Summary 💡

Have the examples in the solid-start/examples/ folder run on stackblitz.

### Examples 🌈

In particular:

https://stackblitz.com/github/solidjs/solid-start/tree/main/examples/bare
https://stackblitz.com/github/solidjs/solid-start/tree/main/examples/basic

### Motivation 🔦
It would be a lot easier to make reproductions.

**Comment by ryansolid** [comment] 2023-12-22 07:22
Its like Async Local Storage is there but not working. Yet...https://stackblitz.com/edit/node-s1d4mv?file=index.js so something is just not configured right.

**Comment by birkskyum** [comment] 2023-12-23 13:56
Duplicate
- #1172

**Comment by nksaraf** [comment] 2023-12-23 18:32
Spoke to the `nitro` team which has spoken to the `stackblitz` team. It seems like there is kindof flkay version of AsyncLocalStorage in stackblitz but nothing really to rely on. I wonder if there is some userland hack possible to enable this.

**Comment by birkskyum** [comment] 2023-12-25 13:14
Is it this?
- https://github.com/stackblitz/webcontainer-core/issues/1169

**Comment by nksaraf** [comment] 2023-12-27 11:49
I think we should close this as duplicate in favor of https://github.com/solidjs/solid-start/issues/1172, since that describes the cause of the issue and will be a better tracking issue for this use case.

**Closed by nksaraf** 2023-12-27 11:49 UTC
Labels: enhancement
