### ISSUE TITLE
TypeScript starter should have `"strict": true` by default

### ISSUE THREAD

**Issue by DaniGuardiola** [solidjs/solid-start#372] opened 2022-10-27 13:57 UTC
I just lost a bit of time fixing uncaught type errors because I had assumed `strict` was enabled in `tsconfig`. Feels like it should be the default (this is the case for the other meta-frameworks I've used). Happy to send a PR if the maintainers agree :)

**Comment by nksaraf** [comment] 2022-10-30 04:56
yeah I agree we should enable! Though it might not work properly yet because of you have to make our internals strict: true since we ship with the typescript.

**Comment by DaniGuardiola** [comment] 2022-11-04 15:44
@nksaraf  right, yeah I guess there'll be some work to do to either fix or ignore issues in the internals :+1:

**Comment by viridia** [comment] 2022-12-03 20:58
@nksaraf As a general rule, there should be no coupling between the tsconfig strictness of a library and the strictness of the code that uses that library. The solution is simple: the package.json "main" entry should not point to uncompiled TypeScript code, but should instead point to a compiled "dist" directory that contains both .js and .d.ts files. Setting things up this way, the TypeScript compiler is no longer required to compile the library code, and the app can be a strict or as non-strict as it wants, independently of the library's compilation options. This is how I have set up my own library builds and it works fairly well.

**Comment by ryansolid** [comment] 2022-12-21 21:55
Duplicate of #140

**Closed by ryansolid** 2022-12-21 21:55 UTC
