### ISSUE TITLE
[Bug?]: Effects and Events do not run importing a Lucide Solid Icon.

### ISSUE THREAD

**Issue by askides** [solidjs/solid-start#1048] opened 2023-09-04 06:24 UTC
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Current behavior 😯

If i write these lines of code:

```tsx
import { createEffect } from "solid-js";
import { DatabaseZapIcon } from "lucide-solid";
import { Alert } from "~/components/ui/alert";

export default function Page() {
  createEffect(() => {
    console.log("Running Effect!");
  });

  return (
    <main class="max-w-lg mx-auto">
      <form method="post" class="space-y-5">
        <Alert class="rounded-lg border-2 border-emerald-500">
          <DatabaseZapIcon class="shrink-0" />
        </Alert>

        <button type="button" onClick={() => console.log("Clicked!")}>
          Submit
        </button>

        <input type="text" onInput={() => console.log("Typed!")} />
      </form>
    </main>
  );
}
```

No console logs will be printed, nether for effect or events.

But everything start working perfectly just commenting the icon.

```tsx
import { createEffect } from "solid-js";
import { DatabaseZapIcon } from "lucide-solid";
import { Alert } from "~/components/ui/alert";

export default function Page() {
  createEffect(() => {
    console.log("Running Effect!");
  });

  return (
    <main class="max-w-lg mx-auto">
      <form method="post" class="space-y-5">
        <Alert class="rounded-lg border-2 border-emerald-500">
          {/* <DatabaseZapIcon class="shrink-0" /> */}
        </Alert>

        <button type="button" onClick={() => console.log("Clicked!")}>
          Submit
        </button>

        <input type="text" onInput={() => console.log("Typed!")} />
      </form>
    </main>
  );
}
```

### Expected behavior 🤔

The expected behavior is the correct running of the effect, and the correct event dispatching of the button click and the input type.

### Steps to reproduce 🕹

Described in the "Current Behavior" tab above.

### Your environment 🌎

```shell
System:
  OS: macOS 13.2.1
  CPU: Apple M1
Binaries:
  Node: v18.17.1
  PNPM: v8.7.0
npmPackages:
  solid-start => ^0.3.5
```

**Comment by edivados** [comment] 2023-09-05 10:19
Can't reproduce. Effect runs regardles of the icon's presence. 
Do you have the same problem on build or is  it only in dev? If you have a repo for reproduction that would be helpful.

Something else I noticed is that in dev all Icons get loaded resulting in 1k+ file requests and slowing everything down quite a lot for me. Not sure if there is some magic vite config to prevent this but couldn't find anything in the lucide-solid docs. I am assuming this has to do with vite not treeshaking in dev and how the icons get exported by lucide-solid.

My env:

```
Template: bare, ts, ssr
System:
  OS: Windows 10
Binaries:
  Node: v20.5.1
  PNPM: v8.7.0
npmPackages:
  solid-start: ^0.3.5
  lucide-solid: ^0.274.0
```

**Comment by askides** [comment] 2023-09-05 17:14
I did some tests, and the problem only occurs in dev, and not in build.

I also confirm the problem you are pointing out that I had not noticed, it is actually downloading the entire list of icons.

I attach screenshots for clarity:

<img width="745" alt="Acquisizione schermata 05 09 2023 alle 19 13 10" src="https://github.com/solidjs/solid-start/assets/9286706/13941220-659f-4ce1-86de-e131175413bd">


For the repo also I have posted the source, here is the link to the route that is giving problems:

https://github.com/askides/solid-start-debug/blob/main/src/routes/test.tsx

**Comment by edivados** [comment] 2023-09-05 18:14
Doesn't look to me like this is something that can be solved in solid-start.

I looked around a bit on the lucide repo and found two issues mentioning this problem but related to svelte.
https://github.com/lucide-icons/lucide/issues/1284
https://github.com/lucide-icons/lucide/issues/1475

Interestingly for svelte it seems to be possible to import a single icon directly which should solve the problem. I would suggest to ask on the repo there.

**Comment by ryansolid** [comment] 2023-12-19 18:51
In setting up for SolidStart's next Beta Phase built on Nitro and Vinxi we are closing all PRs/Issues that will not be merged due to the system changing. If you feel your issue was closed by mistake. Feel free to re-open it after updating/testing against 0.4.x release. Thank you for your patience.  See https://github.com/solidjs/solid-start/pull/1139 for more details.

**Closed by ryansolid** 2023-12-19 18:51 UTC
Labels: bug

**Comment by Christopher2K** [comment] 2023-12-26 17:25
I have a workaround @edivados for the bundling issue using v0.4.x

1. In `vite.config.ts`, we will create the virtual path `lucide-solid/icons` point to the actual `.jsx` icons files. 

```typescript
import { fileURLToPath, URL } from "node:url";
import { defineConfig } from "@solidjs/start/config";

export default defineConfig({
  resolve: {
    alias: {
      "lucide-solid/icons": fileURLToPath(
        new URL(
          "./node_modules/lucide-solid/dist/source/icons",
          import.meta.url
        )
      ),
    },
  },
});
``` 

2. To enable TS support, create a `@types/lucide.d.ts` in your `src` folder
```typescript
declare module "lucide-solid/icons/*" {
  import { LucideProps } from "lucide-solid/dist/types/types";
  import { Component } from "solid-js";
  const cmp: Component<LucideProps>;

  export = cmp;
}
```

3. Your dev server is fast again!

Before:
<img width="346" alt="CleanShot 2023-12-26 at 12 25 13@2x" src="https://github.com/solidjs/solid-start/assets/16650656/9a49b147-9997-48ba-b66d-d81e7b0a2d8e">

After: 
<img width="673" alt="CleanShot 2023-12-26 at 12 23 31@2x" src="https://github.com/solidjs/solid-start/assets/16650656/612a99bb-ed8e-4302-adbc-728ce5bec3b2">

**Comment by vaneworks** [comment] 2024-06-18 13:29
> I have a workaround @edivados for the bundling issue using v0.4.x
> 
> 1. In `vite.config.ts`, we will create the virtual path `lucide-solid/icons` point to the actual `.jsx` icons files.
> 
> ```ts
> import { fileURLToPath, URL } from "node:url";
> import { defineConfig } from "@solidjs/start/config";
> 
> export default defineConfig({
>   resolve: {
>     alias: {
>       "lucide-solid/icons": fileURLToPath(
>         new URL(
>           "./node_modules/lucide-solid/dist/source/icons",
>           import.meta.url
>         )
>       ),
>     },
>   },
> });
> ```
> 
> 2. To enable TS support, create a `@types/lucide.d.ts` in your `src` folder
> 
> ```ts
> declare module "lucide-solid/icons/*" {
>   import { LucideProps } from "lucide-solid/dist/types/types";
>   import { Component } from "solid-js";
>   const cmp: Component<LucideProps>;
> 
>   export = cmp;
> }
> ```
> 
> 3. Your dev server is fast again!
> 
> Before: <img alt="CleanShot 2023-12-26 at 12 25 13@2x" width="346" src="https://private-user-images.githubusercontent.com/16650656/292900395-9a49b147-9997-48ba-b66d-d81e7b0a2d8e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTg3MTcxODksIm5iZiI6MTcxODcxNjg4OSwicGF0aCI6Ii8xNjY1MDY1Ni8yOTI5MDAzOTUtOWE0OWIxNDctOTk5Ny00OGJhLWI2NmQtZDgxZTdiMGEyZDhlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjE4VDEzMjEyOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTkyZDFmNDJjYmUxOTE2OGIzM2NhYTdiY2NhZjkyMzIwYzAwNTM0Y2VmNTYzOTI5ZGIwMjU2NmM1MGVkN2NhMWYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.PL3Mdsu7F-MdCe_J1QKDlgxyxBFYn6UhbBcdcjuiDgw">
> 
> After: <img alt="CleanShot 2023-12-26 at 12 23 31@2x" width="673" src="https://private-user-images.githubusercontent.com/16650656/292900225-612a99bb-ed8e-4302-adbc-728ce5bec3b2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTg3MTcxODksIm5iZiI6MTcxODcxNjg4OSwicGF0aCI6Ii8xNjY1MDY1Ni8yOTI5MDAyMjUtNjEyYTk5YmItZWQ4ZS00MzAyLWFkYmMtNzI4Y2U1YmVjM2IyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjE4VDEzMjEyOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWM2ODk4ODYzMzU1ODkzMDFhMDVmOWNmZGJiODYwNzBlZmJlNWMzOGI2OWE0YjZmYjk4YzliM2U5M2EyOWM1MmEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.6mFg3dgRos8e8wErQrihxKc1KAfVHPR4jxf1gEvt3Nc">

I'm experiencing the same issue where the app is loading every icon, but this did not fix it. Additionally, in the latest version of solid-start, I get this type error when editing the app.config.js:

```
Object literal may only specify known properties, and 'resolve' does not exist in type 'SolidStartInlineConfig'.
```

**Comment by Brendonovich** [comment] 2024-06-18 13:42
@vaneworks vite configuration needs to go in the `vite` object, that might fix it
```ts
import { fileURLToPath, URL } from "node:url";
import { defineConfig } from "@solidjs/start/config";

export default defineConfig({
  vite: {
    resolve: {
      alias: {
        "lucide-solid/icons": fileURLToPath(
          new URL(
            "./node_modules/lucide-solid/dist/source/icons",
            import.meta.url
          )
        ),
      },
    },
  }
});
```

Though I'd suggest using [`unplugin-icons`](https://github.com/unplugin/unplugin-icons) and possibly [`unplugin-auto-import`](https://github.com/unplugin/unplugin-auto-import) for an even easier time with icons, you get access to Lucide + a lot more. Just have to account for [this problem](https://github.com/solidjs/solid-start/issues/1374#issuecomment-2162667748) with auto import.
