### ISSUE TITLE
Adblocker breaks client navigation

### ISSUE THREAD

**Issue by ardauzan** [solidjs/solid-start#852] opened 2023-04-22 09:45 UTC
Hello, I noticed that using an adblocker breaks the client-side navigation (u block origin on firefox and chromium). Is anyone able to replicate this? The path in the address bar gets updated but the ui that belongs to the page I initially entered the app from sticks to the screen. So if I enter from / and want to go to /about using an Anchor the address bar shows /about but the ui is still home page. Islands mode works fine but I don't want to use it. Thx for anwsers.

**Comment by ryansolid** [comment] 2023-04-26 22:31
My guess is it breaks hydration in a silent way but this is going to be hard to reproduce I think.

**Comment by boehs** [comment] 2023-04-26 22:42
Cannot reproduce.

1. Could you sent your ublock configuration?
2. What sites are affected?
3. Any errors in console?

**Comment by BigDog1400** [comment] 2023-05-13 06:41
I have a similar problem. I have a page with SSR, a list, and in each item from the list, a button, the buttons doesn't get hydrated when the page if access via URL, if there is a client side navigation to the URL, it works fine. I tested removing my adblock and it works all right again.

**Comment by ryansolid** [comment] 2023-12-19 17:06
In setting up for SolidStarts next Beta Phase built on Nitro and Vinxi we are closing all PRs/Issues that will not be merged due to the system changing. If you feel your issue was closed by mistake. Feel free to re-open it after updating/testing against 0.4.x release. Thank you for your patience.  See https://github.com/solidjs/solid-start/pull/1139 for more details.

**Closed by ryansolid** 2023-12-19 17:06 UTC
