### ISSUE TITLE
[Bug?]: API routes do not import objects properly from `"use server"` files.

### ISSUE THREAD

**Issue by elliotwaite** [solidjs/solid-start#1283] opened 2024-01-25 12:32 UTC
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Current behavior 😯

If I have an API route that imports an object from a file that has `"use server"` at the top of it, it does not properly import the object and instead imports an empty object.

Demo on StackBlitz [here](https://stackblitz.com/edit/solid-start-import-from-use-server?file=src%2Fapp.tsx).

Is this a bug, or am I using `"use server"` incorrectly? I thought that adding `"use server"` to the top of the file meant that the contents of that file would only be available server-side. And since API routes only run server-side, I thought they would still be able to import from those files. But when I add `"user server"` to the top of the files I'm importing from, it seems to break things.

### Expected behavior 🤔

For API routes to be able to import from files that have `"use server"` at the top of them.

### Steps to reproduce 🕹

Steps:

1. Open [this StackBlitz demo](https://stackblitz.com/edit/solid-start-import-from-use-server?file=src%2Fapp.tsx).
2. Run `pnpm dev`
3. Click the different links to see the different returned values from the API routes.

**Comment by lxsmnsyc** [comment] 2024-01-25 12:44
Must be a bundling issue

**Comment by ryansolid** [comment] 2024-01-25 20:29
"use server" top of the file means these are RPC functions that are exported so any import in the client will call them as fetch requests. It is not a general mechanism to say things are server only. I imagine it is an empty object because we wrap every export with a proxy that is looking for specific properties. So in a sense I guess it might be working if I had the proxy do passthrough. However, it is misleading because it isn't guaranteed to be server only. While it might be hard for us to determine this at compile time I think we should probably error at runtime on the server if we notice that what we get isn't a function.

**Comment by ryansolid** [comment] 2024-01-25 21:49
I've added an error to the server registration of server functions which should help make this clearer. So we need better docs in general. But I'm closing this by design.

**Closed by ryansolid** 2024-01-25 21:49 UTC
Labels: bug

**Comment by elliotwaite** [comment] 2024-01-25 21:53
Ah, I see. I was misunderstanding what `"use server"` did. Thanks for the explanation.
