### ISSUE TITLE
Using the MDX starter and HMR doesn't work

### ISSUE THREAD

**Issue by devramsean0** [solidjs/solid-start#532] opened 2022-12-10 21:11 UTC
Title says it all really, no mdx pages hot reload, neither do the .tsx files

**Comment by zachschultz** [comment] 2023-03-21 02:29
I'm also running into issues with the MDX starter, but with hydration, e.g.,
```
Error: Unrecoverable Hydration Mismatch. No template for key: 0-0-0-0-0-0-0-0-0-1-0-0-4-0-1-1-0-0-1
```

Hot reloading is actually working fine for me, but when I refresh the page I get "Unrecoverable Hydration Mismatch" errors.

**Comment by ryansolid** [comment] 2023-03-21 06:55
Yeah this hydration issue seems to be related to the Vite 4.0 update. Downgrading to Vite 3.1.2 seems to fix it. HMR I can't speak to yet.

**Comment by DaniGuardiola** [comment] 2023-04-17 20:44
I can confirm that on latest (0.2.26) this happens on my project with Vite 4.1+, downgrading works.

**Comment by wakaztahir** [comment] 2023-09-10 12:50
@ryansolid I am experiencing this issue, when I use Dynamic component

Here's the codebase : https://github.com/Qinetik/Anique

To experience the error, You need to turn on `ssr` in vite config in demo, that's it as soon as you turn on `ssr` you start getting the error, There's a `ErrorBoundary` which catches this error and displays it here
https://github.com/Qinetik/anique/blob/5107c7cad73c8de3f5311882efe269ea7d24b1e0/styled/src/base.tsx#L170

so if you remove this Dynamic component, the error is gone but also is the site because the whole site uses this

The website works completely when `ssr : false`

The project is configured, pnpm updated, everything wired good, run start in the root folder

so how can I fix it ?

**Comment by iacore** [comment] 2023-09-27 07:27
I think I may have found the issue. MDX creates code like this:

```js
2  |  const MDXLayout = "/src/Main.mdx";
3  |  function _createMdxContent(props) {
4  |    return <></>;
   |                 ^
5  |  }
6  |  function MDXContent(props = {}) {
```

**Comment by darrenbarklie** [comment] 2023-10-02 23:32
@iacore – Thanks for the tip, I also encountered this error by inadvertently placing a semi-colon after my return statement:
```ts
export default function Index() {
  return (
    <>
      ...
    </>
  ); // incorrect semi-colon
}
```

**Comment by ryansolid** [comment] 2023-12-18 23:23
In setting up for SolidStarts next Beta Phase built on Nitro and Vinxi we are closing all PRs/Issues that will not be merged due to the system changing. If you feel your issue was closed in mistake. Feel free to re-open it after updating/testing against 0.4.x release. Thank you for your patience.  See https://github.com/solidjs/solid-start/pull/1139 for more details.

**Closed by ryansolid** 2023-12-18 23:23 UTC
Labels: bug, mdx

**Comment by iacore** [comment] 2023-12-19 10:02
Was this more like a MDX+Solid problem without SolidStart?
