### ISSUE TITLE
[astro] Server environment variables in preview mode 

### ISSUE THREAD

**Issue by dertieran** [solidjs/solid-start#853] opened 2023-04-25 07:24 UTC
I'm testing out the astro integration from `solid-start@0.3.0-alpha.3` in an existing `0.2.26` project.

I had some server only environment variables in a `.env` file.

```env
DATABASE_URL=<some database url>
```

I changed the usage from `process.env` to `import.meta.env` according to the [astro docs](https://docs.astro.build/en/guides/environment-variables/).
_(Using `process.env` also still worked when running `astro dev`)_

```diff
- const DATABASE_URL = process.env.DATABASE_URL;
+ const DATABASE_URL = import.meta.env.DATABASE_URL;
if (!DATABASE_URL) throw new Error('No database url defined')
```

But when I then ran `astro build` and then `astro preview` the environment variables where not defined.

I already debugged this a bit and noticed

Astro either converts or inlines the `import.meta.env` without a prefix.
https://github.com/withastro/astro/blob/b24607069ed1b305b47ca25171e682f7c71603eb/packages/astro/src/vite-plugin-env/index.ts#L30-L39

Because the `.env` is loaded in the build step the code above is basically converted back to

```js
const DATABASE_URL = process.env.DATABASE_URL;
```

But the `.env` file is not loaded when running `astro preview` so `process.env.DATABASE_URL` is not defined.

Not sure if this should be the responsibility of `solid-start` or could also be handled by `@astrojs/node`.

I fixed it for me right now by importing this `env.js` file

```js
import dotenv from "dotenv";
dotenv.config();
```

In [`handler.js`](https://github.com/solidjs/solid-start/blob/919023d8dcea3c46898e428d86cf0eb31487e622/packages/start/astro/handler.js)

```js
import "./env.js";
import startHandler from "~/entry-server";
```

So I could test the build locally, but not sure if this is a good solution.

**Comment by ryansolid** [comment] 2023-04-29 21:35
You probably understand the issue better than I do at the moment. I noticed it was broken but wasn't sure what solution aligned with Astro the best. Things to note are I'm bypassing Astro for the client build. This is probably fine for public stuff as long as I set the Vite prefix appropriately to match their conventions. And I'm gathering the issue is on the server build. You are saying if I understand start is loading the env during the build and that causes Astro not to inline it. If so we should probably stop doing that and rely on Astro's mechanism. 

This is super helpful information.

**Comment by birkskyum** [comment] 2023-07-12 21:22
@dertieran , it seems like this is fixed. Can you verify if that is the case with 0.3.0-alpha.7?

**Comment by dertieran** [comment] 2023-07-18 10:29
Hey 👋
Sorry I was on vacation for a few weeks and didn't check Github for a while.
Yes the `0.3.0-alpha.7` update fixed it for me, so I guess this issue can be closed.

**Comment by birkskyum** [comment] 2023-07-18 10:41
@dertieran , can you close it?

**Closed** 2023-07-18 10:54 UTC
