### ISSUE TITLE
Vitest close time-out

### ISSUE THREAD

**Issue by aminya** [solidjs/solid-start#887] opened 2023-05-21 04:15 UTC
When using the `solid-start/vite` plugin inside Vitest, I get this error:
```
close timed out after 10000ms
```

I tried many different configurations, but it didn't help. I wonder what is happening here.

` vitest.config.test`
```ts
import { defineConfig } from "vitest/config";
import config from "./vite.config";

export default defineConfig({
  ...config,
  test: {
    deps: {
      registerNodeLoader: true,
      inline: [/solid-js/],
    },
    environment: "happy-dom",
    globals: false,
    coverage: {
      provider: "c8",
    },
    setupFiles: ["./vitest.config.setup.ts"],
    transformMode: { web: [/\.[jt]sx?$/] },
  },
});

```

where `vitest.config.setup.ts` is
```ts
import "@testing-library/jest-dom";
```

**Comment by jean343** [comment] 2023-06-16 19:20
I am having the exact same vitest error. I also believe it's caused by the `solid-start-file-system-router` plugin.

I have written this little hack to skip the plugin in tests:

```js
import node from "solid-start-node";
import solid from "solid-start/vite";
import { defineConfig } from "vite";

let solidPlugins = solid({ adapter: node(), inspect: false });
solidPlugins = solidPlugins.filter((plugin) => {
  switch (plugin.name) {
    case "solid-start-file-system-router":
      plugin.configureServer = () => undefined;
      return plugin;
    default:
      return plugin;
  }
});

export default defineConfig({
  plugins: [solidPlugins],
});

```

**Comment by atk** [comment] 2023-06-16 19:48
Which node version are you using?

**Comment by jean343** [comment] 2023-06-19 13:20
I am using the latest LTS version at this time.

```
node -v
v18.16.0
```

**Comment by RobertoVillegas** [comment] 2023-07-19 08:36
I have the same issue if I use any newer version of vitest. It works correctly with vitest `^0.26.3`.

**Comment by ryansolid** [comment] 2023-12-19 17:18
In setting up for SolidStarts next Beta Phase built on Nitro and Vinxi we are closing all PRs/Issues that will not be merged due to the system changing. If you feel your issue was closed by mistake. Feel free to re-open it after updating/testing against 0.4.x release. Thank you for your patience.  See https://github.com/solidjs/solid-start/pull/1139 for more details.

**Closed by ryansolid** 2023-12-19 17:18 UTC
