### ISSUE TITLE
Using createServerAction$ outside the route throws an error

### ISSUE THREAD

**Issue by maksimsemenov** [solidjs/solid-start#326] opened 2022-10-17 13:46 UTC
I was trying to use a `createServerAction$` outside a route component: I was hoping to reuse this function in multiple routes and have it be part of the set of business logic hooks that I can share between components/routes.

When I do that, I get an error: `Make sure your app is wrapped in a <Router />`.

Packages versions:
| Package | Version |
|-----|------|
| @solidjs/meta | 0.28.0 |
| @solidjs/router | 0.5.0 |
| solid-js | 1.5.7 |
| solid-start | 0.1.6 |
| solid-start-node | 0.1.6 |
| vite | 3.1.3 |

Not sure if it is a deliberate decision and if it is supposed to work this way. If it is, then maybe it can be added to the docs because, right now, it is not clear that it can be used only in routes.

**Comment by ryansolid** [comment] 2022-10-17 18:50
It should be able to be used outside of the routes folder to my knowledge but it still needs to be defined inside a component since it uses context to know the location. The function itself can be extracted though and reused in multiple locations. If that makes sense.

Want to make sure we are talking about the same thing.

**Comment by maksimsemenov** [comment] 2022-10-17 19:43
I created a small [eproducible demo](https://github.com/maksimsemenov/solid-start-server-action-test):
If I import `createServerAction$` in `src/modules/api/hooks.ts`, then I get this `Make sure your app is wrapped in a <Router />` error. If I remove/comment it, then everything works normal.

So my idea was to define in some common folder, so it can be used across multiple routes. But seems, that it is not how it supposed to be used and it should be defined in specific route. Is that correct?

Can it be defined in the "api" route file (without the component)?

**Comment by nksaraf** [comment] 2022-10-17 21:44
```ts
function createEntityAction() {
    return createServerAction$<Entity, Entity>(
        async(atributes: Entity): Promise<Entity> => {
            return atributes
        }
     )
}
```

Now this helper can be used any number of components.. but declaring the action globally is dangerous because on the server all users would get access to the same action controller, and thats why we are seeing the error. Because you can't access the router context if you call this outside a component.

**Comment by nksaraf** [comment] 2022-10-17 22:23
Closing, since its not a bug. Maybe we should actually have a better error message in case people are trying to do what you are trying and get hit by this.

**Closed by nksaraf** 2022-10-17 22:23 UTC

**Comment by maksimsemenov** [comment] 2022-10-18 00:05
Thanks, @nksaraf. Could you please elaborate a little bit more on:
> but declaring the action globally is dangerous because on the server all users would get access to the same action controller, and thats why we are seeing the error. Because you can't access the router context if you call this outside a component.

Are these mostly security concerns (like all users will share the same execution context)? Or something else?
Will I still be able to get user data from the request headers?

I'm just trying to understand all limitations of this approach.

**Comment by nksaraf** [comment] 2022-10-18 00:37
So there are two different aspects because of which this is problematic:

1. Context access: Most of these functions like `createServerData$`, `createRouteData`, `createServerAction$`, `createRouteAction`, require access to context providers, like solid-start's inbuild `ServerContext`, or the router's `RouterContext`. The `ServerContext` actually gives these methods access to the ongoing user request (and the headers). So they need to be called inside the component tree to get access to the context providers. 

Imagine, multiple requests to the server at the same time and they all are rendering at the same time. Its the context providers that make sure that for each different user, `createServerData$` will give you access to the correct `request`. If it was called globally it would not know which user's request is it rendering.

2. This leads to problem two. On the server, whatever you declare globally will be used by all the users who come to the site. So any statefulness is going to cause weird interleaving behaviour. Sometimes we think we can avoid this because we deploy to serverless environments, but even there a warm serverless handler will reuse the global objects for all your users. The only way to isolate things to a specific user, is to do things inside the component tree so that a new instance is created for every user and they don't share. Almost nothing should be shared between your users. 

You have to be extremely deliberate about what you allow to be global. Anything that uses context by default needs to be local to one run of the component tree. And it should not be mixed with other runs.

**Comment by maksimsemenov** [comment] 2022-10-18 00:46
Thanks, @nksaraf. That is very helpful.
